wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683351835.123349
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 1
      - 3
      - 5
      10:
      - 9
